// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWLVpZNdU0c09rjImysCSs-1yWUKPLTDo',
    appId: '1:567945579519:android:543e82a17e76a5389b35ca',
    messagingSenderId: '567945579519',
    projectId: 'arise-and-shine-tanzania',
    storageBucket: 'arise-and-shine-tanzania.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaUV06G4XMs1r5gV43jDRy9uqu36I9jew',
    // Must match ios/Runner/GoogleService-Info.plist (GOOGLE_APP_ID), not
    // the Android app ID. Passing the Android ID on iOS initializes the
    // Firebase SDK with a different registered app.
    appId: '1:567945579519:ios:f3611026a96df3b29b35ca',
    messagingSenderId: '567945579519',
    projectId: 'arise-and-shine-tanzania',
    storageBucket: 'arise-and-shine-tanzania.firebasestorage.app',
  );
}
